
name: .NET Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: VideoHarvester.sln
      Project_Path: VideoHarvester\VideoHarvester.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Add MSBuild to the PATH
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      run: dotnet restore $env:Solution_Name

    # Build the application
    - name: Build the application
      run: dotnet build $env:Solution_Name --configuration ${{ matrix.configuration }} --no-restore

    # Execute all unit tests in the solution (if any exist)
    - name: Execute unit tests
      run: dotnet test $env:Solution_Name --configuration ${{ matrix.configuration }} --no-build --verbosity normal
      continue-on-error: true

    # Publish the application
    - name: Publish the application
      if: matrix.configuration == 'Release'
      run: dotnet publish $env:Project_Path --configuration Release --output ./publish --no-build

    # Upload build artifacts
    - name: Upload build artifacts
      if: matrix.configuration == 'Release'
      uses: actions/upload-artifact@v4
      with:
        name: VideoHarvester-Release
        path: ./publish
